### ISSUE TITLE
Is there a way to make the code automatic?

### ISSUE THREAD

**Issue by mathbsouza** [gregorias/anki-word-hyphenator#27]
I think it is very good, but the problem is having to click the hyphenation button every single time. Isn’t there a way to make it automatic?

**Comment by gregorias** [comment]
Sounds good, I wonder why haven’t I done this already…

**Comment by mathbsouza** [comment]
> Sounds good, I wonder why haven’t I done this already…

After the update, the add-on is not working, and the button is not appearing anymore 😮.

**Comment by gregorias** [comment]
I submitted a wrong package, it should be fixed now.

**Comment by gregorias** [comment]
I should be able to have some experimental version tomorrow.
